export const PERMISSIONS = [
  "org.view",
  "org.create",
  "org.manage",
  "member.view",
  "member.create",
  "member.edit",
  "member.void",
  "user.view",
  "user.create",
  "user.edit",
  "user.deactivate",
  "role.view",
  "role.manage",
  "settings.org.manage",
  "settings.membership_type.manage",
  "settings.member_status.manage",
  "settings.payment_mode.manage",
  "settings.income_category.manage",
  "settings.expense_category.manage",
  "settings.whatsapp.manage",
  "audit.view",
  "financialyear.view",
  "financialyear.manage",
  "fee.view",
  "fee.assign",
  "fee.waive",
  "payment.view",
  "payment.create",
  "payment.void",
  "receipt.view",
  "income.view",
  "income.create",
  "income.void",
  "expense.view",
  "expense.create",
  "expense.void",
  "report.view",
  "whatsapp.view",
  "whatsapp.send",
  "notification.view",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

export const PERMISSION_SET: ReadonlySet<string> = new Set(PERMISSIONS);
